instance:
  app: SPRING-CLOUD-EUREKA-CLIENT
  instanceId: localhost:spring-cloud-eureka-client:8090
  hostName: localhost
  securePort:
    "$": 443
    "@enabled": false
  ipAddr: localhost
  status: UP
  leaseInfo:
    renewalIntervalInSecs: 15
    durationInSecs: 15
  statusPageUrl: http://localhost:8090/api/v1/documentation
  healthCheckUrl: http://localhost:8090/api/v1/
  secureVipAddress: spring-cloud-eureka-client
  port:
    "$": 8090
    "@enabled": true
  vipAddress: spring-cloud-eureka-client
  dataCenterInfo:
    "@class": com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo
    name: MyOwn
eureka:
  port: 8761
  host: localhost
  servicePath: /eureka/apps/